const CONSTANTS = {
    LOGIN: 'LOGIN',
    SET_SESION: 'SET_SESION',
    LOGOUT : 'LOGOUT ',
    LOAD_COMPLETE:'LOAD_COMPLETE',
    SET_LOADING:'SET_LOADING',
    STOP_LOADING:'STOP_LOADING',
    OPEN_MODAL:'OPEN_MODAL',
    CLOSE_MODAL:'CLOSE_MODAL',
    OPEN_ALERTRESPONSE:'OPEN_ALERTRESPONSE',
    CLOSE_ALERTRESPONSE:'CLOSE_ALERTRESPONSE',
    OPEN_ALERTRESPONSE_DELETE:'OPEN_ALERTRESPONSE_DELETE',
    OPEN_ALERTRESPONSE_UPDATE:'OPEN_ALERTRESPONSE_UPDATE',
    CLEAN_IMAGE_LOGOEMPLOYER:'CLEAN_IMAGE_LOGOEMPLOYER',
    LOAD_IMAGE_LOGOEMPLOYER:'LOAD_IMAGE_LOGOEMPLOYER',
    GET_DATAEMPLOYER:'GET_DATAEMPLOYER',
    DATAEMPLOYER:'DATAEMPLOYER',
    TYPE_USER:'TYPE_USER',
    GET_URL_IMAGE:'GET_URL_IMAGE',
    LOAD_EMPLOYER_PROFILE_COMPLETE:'LOAD_EMPLOYER_PROFILE_COMPLETE',
    SET_LOCATION:'SET_LOCATION',
    SAVE_LOCATION:'SAVE_LOCATION',
    UPDATE_LOCATION:'UPDATE_LOCATION',

    //Images
    PATH_LOGO_EMPLOYER : 'LOGO_EMPLOYER',
    
    //APP
    GET_FORM:'GET_FORM',
    SET_FORM:'SET_FORM',
    GET_DATA_LANGUAGE:'GET_DATA_LANGUAGE',
    SET_DATA_LANGUAGE:'SET_DATA_LANGUAGE',
    UPLOAD_IMAGE:'UPLOAD_IMAGE',
    LOAD_IMAGE:'LOAD_IMAGE',
    SAVE_IMAGE:'SAVE_IMAGE',

    //REGISTER
    REGISTEREMPLOYEE:'REGISTEREMPLOYEE',
    REGISTEREMPLOYER:'REGISTEREMPLOYER',

    //UPDATE
    UPDATEDATAEMPLOYER:'UPDATEDATAEMPLOYER',
    UPDATEDATAEMPLOYEE:'UPDATEDATAEMPLOYEE',

    //GETDATA
    GET_EMPLOYES     : 'GETEMPLOYES',

    //USER
    GET_DATA_USER    : 'GET_DATA_USER',
    DATA_USER        : 'DATA_USER',
    UPDATE_DATA_USER : 'UPDATE_DATA_USER',

};

export default CONSTANTS;

